### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mambrosicds** [PDF417/pdf417-android#14]
I'm having this error trying to use the library as a .jar, extracting it from the .aar file.
I've added the **.so** files and the **res/raw/device_list.json** file as well.

The error is showing up when i try to instantiate the RecognizerView programatically inside my Activity's onCreate method:

```javascript
mRecognizerView = new RecognizerView(this);
```

And this is the stack trace:

    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at com.microblink.secured.llIIIlllll.<init>(line:67)
    at com.microblink.secured.IllIIIIllI.<init>(line:59)
    at com.microblink.view.BaseCameraView.IllIIIllII(line:241)
    at com.microblink.view.BaseCameraView.<init>(line:212)
    at com.microblink.view.recognition.RecognizerView.<init>(line:131)
    at com.acuant.mobilesdk.detect.PDF417.CameraPDF417.onCreate(CameraPDF417.java:139)
    at android.app.Activity.performCreate(Activity.java:5990)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
    at android.app.ActivityThread.access$800(ActivityThread.java:151) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5254) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

The obfuscated code for the **com.microblink.view.BaseCameraView.IllIIIllII(line:241)** line looks something like this:

```javascript
String[] var3 = var2.split("::");
this.IllIIIIllI = var3[1];
this.llIIIlllll = var3[0];
JSONArray var4;
if(var1.has("previewSize")) {
   var4 = var1.getJSONArray("previewSize");
    this.llIIlIlIIl = new llIIlIlIIl(var4.getInt(0), var4.getInt(1));
 }
```

It seems that the code is trying to parse the device_list.json file which doesn't seem to be malformed.

**Comment by DoDoENT** [comment]
Hi, this exception indicates a malformed device_list.json. Are you trying to use old version of device_list.json with new version of library? Keep in mind that device_list.json's format has been changed  since v5.0.0.

**Comment by mambrosicds** [comment]
Hi, thank your quick response!

Yeah, i figured that, but i'm really confused still because i'm using both **classes.jar** and **device_list.json** files contained inside https://github.com/PDF417/pdf417-android/blob/master/LibRecognizer.aar.

The weird thing is that if i remove the **device_list.json** file from my project, the error i get is the same rather than a "couldn't find the .json file" error.

**Comment by DoDoENT** [comment]
Why are you not using AAR directly? It would make you life much simpler. Check if your application project contains res/raw/device_list.json. If it does, then this file will be used instead the file from AAR or from your library project containing that file. Make sure this file is in the latest format.

**Comment by mambrosicds** [comment]
Ok, i'm working on the gradle/Android Studio integration. I think we can close this issue for now.

Thank you!

**Comment by DoDoENT** [comment]
If using Android Studio/gradle, the easiest way is to integrate via [Maven](https://github.com/PDF417/pdf417-android#using-gradle-or-android-studio).

**Comment by mambrosicds** [comment]
The issue i'm having is that this project is actually a library which needs to have PDF417 already integrated. 
Trying to include PDF417 into our library project we found that when using the gradle library plugin it won't let you integrate remote libraries. That's why we need to find a way to do an integration like if we were using eclipse.

My question is, how can i be sure that i'm using the last format for the .json file? i couldn't find that on the documentation

**Comment by mambrosicds** [comment]
Ok, this is embarrassing. It seems that we already had a file in the main application which was, as you mentioned, overwriting the one i was putting in our SDK.

Now it's working perfectly! Thank you and sorry for the trouble!
