### ISSUE TITLE
IllegalStateException on Camera Random 

### ISSUE THREAD

**Issue by skryshtafovych** [PDF417/pdf417-android#42]
Application at random will close and Throw below Errors from SDK.

### Environment Details

**PDF417 version:**-----7.0.0

**Device model:**-----Samsung s8+

**Device Android version:**-----7.0

**Device ABI (processor architecture, e.g. ARMv7):**

Caused by java.lang.IllegalStateException: Native part is already initialized!
       at com.microblink.hardware.camera.camera1.frame.Camera1PreviewFrame.llIIlIlIIl(line:65)
       at com.microblink.view.recognition.RecognizerRunnerView$6.onCameraFrame(line:1034)
       at com.microblink.secured.IlIIlllIIl$1.onPreviewFrame(line:226)
       at com.nexperience.android.mock.MockCamera$MockedPreviewCallback.onPreviewFrame(MockCamera.java:353)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1133)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at com.microblink.secured.lllllIIIlI.run(line:58)

Fatal Exception: java.lang.RuntimeException: Processing queue Camera1 halted due to an error.
       at com.microblink.secured.lllllIIIlI$1.run(line:72)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
[gov.ca.lot.calotteryapp_issue_2367_crash_5ACBC40D018F0001584EFDEAB0D45EBE_DNE_0_v2.txt](https://github.com/PDF417/pdf417-android/files/1891770/gov.ca.lot.calotteryapp_issue_2367_crash_5ACBC40D018F0001584EFDEAB0D45EBE_DNE_0_v2.txt)

**Comment by i1E** [comment]
Hi @skryshtafovych, 

can you explain how and why are you mocking the camera. This is not a standard use case for our SDK and exception is thrown when the same frame is being initialised multiple times for some reason.

**Comment by skryshtafovych** [comment]
We have these devices in Perfecto cloud testing solution. Our testers use it to automate our application. We get this error when moving between 2 screen (One with Camera other with Static Views) that are controlled by a tablayout.
[](https://www.perfecto.io/)
