### ISSUE TITLE
Crash when starting with no additional arguments

### ISSUE THREAD

**Issue by JonasPrap** [PDF417/pdf417-android#7]
Lib crashes when trying to start it without any arguments

                Intent intent = new Intent(FormActivity.this, Pdf417ScanActivity.class);
                startActivityForResult(intent, PDF417MOBI_INTENT_KEY);

```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxx/mobi.pdf417.activity.Pdf417ScanActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2394)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at mobi.pdf417.activity.Pdf417ScanActivity.createRecognizerView(line:134)
            at net.photopay.activity.BaseScanActivity.onCreate(line:205)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

Library is:
android:versionCode="114" android:versionName="3.5.1"

However just by modifying like this it starts working:

                Pdf417MobiSettings sett = new Pdf417MobiSettings();
                Intent intent = new Intent(FormActivity.this, Pdf417ScanActivity.class);
                intent.putExtra(Pdf417ScanActivity.EXTRAS_SETTINGS, sett);
                startActivityForResult(intent, PDF417MOBI_INTENT_KEY);

**Comment by ismolkovic** [comment]
Hi Jonas,

thanks for reporting this. It's necessary to send Pdf417MobiSettings via intent. We will fix this issue in next release.

Best regards,
Igor.

**Comment by DoDoENT** [comment]
This is now handled differently in 4.x API (array of recognizer settings - see the [documentation](https://github.com/PDF417/pdf417-android#recognitionSettingsAndResults)
