### ISSUE TITLE
ClassCastException on setDontShowDialog

### ISSUE THREAD

**Issue by JonasPrap** [PDF417/pdf417-android#8]
Pdf417MobiSettings sett = new Pdf417MobiSettings();
                sett.setDontShowDialog(false);

                Intent intent = new Intent(FormActivity.this, Pdf417ScanActivity.class);
                intent.putExtra(Pdf417ScanActivity.EXTRAS_SETTINGS, sett);
                startActivityForResult(intent, PDF417MOBI_INTENT_KEY);

Trows out in log:

```
W/PhotoPay.cpp:328﹕ Either license key or context is NULL! Will use free license...
Key photopaymode expected Boolean but value was a java.lang.Integer.  The default value false was returned.
 Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
            at android.os.Bundle.getBoolean(Bundle.java:864)
            at net.photopay.settings.llIIlIlIIl.lIlllIlIlI(line:86)
            at net.photopay.view.recognition.BaseRecognizerView.lIllIIlIIl(line:434)
            at net.photopay.view.BaseCameraView.llIIlIlIIl(line:331)
            at net.photopay.view.recognition.BaseRecognizerView.llIIlIlIIl(line:83)
            at net.photopay.view.BaseCameraView.create(line:311)
            at net.photopay.view.recognition.BaseRecognizerView.create(line:78)
            at net.photopay.view.recognition.Pdf417MobiView.create(line:59)
            at net.photopay.activity.BaseScanActivity.onCreate(line:261)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2452)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5586)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ismolkovic** [comment]
Hi Jonas,

this exception is completely harmless. Exception is always thrown not just in this case.

Best regards,
Igor.
